### ISSUE TITLE
Adding API constants for retweeting and likes.

### ISSUE THREAD

**Issue by karthik-sivadas** [chatwoot/twitty#16]
As chatwoot uses Twitty for handling API calls to Twitter some API's needed for the issue chatwoot/chatwoot#1737 is missing for retweets and likes. 
We need to add these constants.

**Comment by karthik-sivadas** [comment]
@sojan-official Is it ok if I add all the API related to tweets in this issue? https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/overview. At present only one API is present.

**Comment by sojan-official** [comment]
@karthik-sivadas  feel free to go ahead.
