### ISSUE TITLE
chore: Add rubocop to the Circle CI build step

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/twitty#21]

**Comment by karthik-sivadas** [comment]
@sojan-official I would like to take up the task and sorry for the delay in pushing this in the previous PR. Just want to confirm if I should use the same rubocop.yml as chatwoot/chatwoot or use something like https://github.com/Shopify/ruby-style-guide/

**Comment by sojan-official** [comment]
@karthik-sivadas  no worries. let's follow the same file in chatwoot/chatwoot

**Comment by sojan-official** [comment]
closed via https://github.com/chatwoot/twitty/pull/22
